## Pour lancer, ansible-playbook --user=root maj.yaml ##

- hosts: serveurs
  tasks:       
    - name: Mise a jour
      become: true
      become_user: root
      apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day	
       force_apt_get: true
